Fer html [Botón, Carta Base y Campanita] (◕‿◕)♡
Fer-Rodriguez/PAE pull request #1
Opened 2022-04-12 22:21 UTC by Fer-Rodriguez

/ᐠ｡ꞈ｡ᐟ\

2022-04-14 00:14 UTC, Vilkas99 commented on src/App.tsx
Librerias Externas => CSS => Componentes => Interfacea
(Todo bien :) )

2022-04-14 00:15 UTC, Vilkas99 commented on src/components/Bell/index.tsx
> +//import { IconName } from "react-icons/bi";
Comentario: De la línea 1 - 3 sintetizar los imports en un sólo statement: 

`import { Avatar, AvatarBadge, AvatarGroup, Stack, HStack, VStack } from "@chakra-ui/react";`

2022-04-14 00:31 UTC, Vilkas99 requested changes
He ahí mis comentarios mi buen Fer! TQM no me odies (Y si tienes dudas, mándame mensaje  ;*)

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Bell/index.tsx
> +
El componente no es una función anónima (Ej: `const Bell = () => ()`. Es necesario transformarla (Recuerda que el snippet RAFC lo hace por ti)

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Bell/index.tsx
> +
Tu componente no tiene funciones dentro, u otras declaraciones de lófica, así que los `{}` y el _return_ está sobrando, aquello lo puedes evitar con la siguiente forma: 

`const Prueba = () => (<h1>Prueba</h1>)`  => Nótese la omisión del return y las llaves.

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Button/index.tsx
> +
Mismo problema que con Bell => La función no es anónima y el return y las llaves vienen sobrando.

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Card/index.tsx
> +import { Box } from "@chakra-ui/react";
Resumir los 3 imports de Chakra en una sóla línea :D

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Card/index.tsx
> +        width="850px"
Evaluar dimensiones, ya que no deberían ser con unidades fijas (Podrías utilizar REM o EM por ejemplo)

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Card/index.tsx
> +        rounded={30}
Modificar el valor del rounded con el fijo del tema (En caso de no tener acceso mal tema, añadir un TODO que evidencía el propósito de modificarlo más tarde)

2022-04-14 00:31 UTC, Vilkas99 commented on src/components/Card/index.tsx
> +            {/* Título */}
Comentarios SUPER BIEN pero puedes abstraer este ENORME componente en más subcomponentes (Por ejemplo, Titulo , subítulo, etc..)

2022-04-14 00:31 UTC, Vilkas99 commented on src/App.tsx
> +      <Bell />
Elimina las llamadas Bell y Card y solo déjale el Provider de Chakra :D

2022-04-14 05:00 UTC, Vilkas99 requested changes

2022-04-14 05:29 UTC, myrosandrade89 requested changes
Revisa los comentarios de los files :D

2022-04-14 05:29 UTC, myrosandrade89 commented on src/components/Bell/index.tsx
> +import { IconButton } from "@chakra-ui/react";
Deberías de utilizar una tabla (como la del componente de Uzi) en lugar del Menu.
Recuerda dejar responsivas las notificaciones y que el contenido se pase a través de props.children, no hardcodear.

2022-04-14 05:29 UTC, myrosandrade89 commented on src/components/Button/index.tsx
> +import { Button } from "@chakra-ui/react";
Falta importar los temas para el componente (hover, boxshadow, active, etc.)

2022-04-15 03:46 UTC, Vilkas99 approved these changes

2022-04-15 17:17 UTC, myrosandrade89 requested changes
- [ ] El componente BaseCard no funciona ;n; 
- [ ] Deberías de verificar tus props de BaseCard (ver comentarios)
- [ ] Deberías utilizar una tabla para las notificaciones de Bell
- [ ] Al ButtonGeneric le falta definir props hover, boxshadow, fontColor

2022-04-15 17:17 UTC, myrosandrade89 commented on src/components/BaseCard/index.tsx
> +import { Box, Grid, GridItem, Center } from "@chakra-ui/react";
No me aparece correctamente el elemento cuando lo corro :c

2022-04-15 17:17 UTC, myrosandrade89 commented on src/components/BaseCard/index.tsx
> +interface IBaseCard {
¿No crees que el margin, padding y shadow deberían ser props ya definidos en lugar de que el programador los modifique?

2022-04-15 17:17 UTC, myrosandrade89 commented on src/components/Bell/index.tsx
> +//Chakra Components
Deberías de utilizar una tabla (como la del componente de Uzi) en lugar del Menu.

2022-04-16 17:07 UTC, myrosandrade89 approved these changes

2022-04-16 18:37 UTC, merged

2022-04-19 01:07 UTC, Vilkas99 reviewed
Todo bien!:D