RadioButton and PopOver components
Fer-Rodriguez/PAE pull request #3
Opened 2022-04-14 03:36 UTC by myrosandrade89

2022-04-14 04:34 UTC, Vilkas99 requested changes
¡Súper bien tu código, Myros! Bien legible y entendible c:

2022-04-14 04:34 UTC, Vilkas99 commented on src/App.tsx
> +        size={"s"}
Todo funciona a la  perfección! Sólo resta eliminar el popOver de este App.tsx, para así dejarlo solito.

2022-04-14 04:34 UTC, Vilkas99 commented on src/components/popOver/index.tsx
> +import {
El orden de la importación no es correcto. 

Debería ser: 

1. React. 
2. Componentes y funciones de librerias externas. 
3. Componentes propios 
4. Interfaces, tipos y enums.

2022-04-14 04:34 UTC, Vilkas99 commented on src/components/popOver/index.tsx
> +  const calculateWidth = (size: string) => {
Añadir el tipo de valor de regreso de la función (En este caso, sería un "number")

2022-04-14 04:34 UTC, Vilkas99 commented on src/components/popOver/index.tsx
> +    if (size == "s") {
Nunca hacer comparaciones con solo 2 "=="  (Siempre utilizar triple verificación: "===") y tampoco hacer comparaciones a literales (En este caso, chars), para ello, siempre utilizar Enums. 

Por ejemplo: 
`enum ETypeSize {
 s, 
m, 
l
}
`

Y después, para usarle, sería algo así: 
`if (size ===  ETypeSize.s){...}`

2022-04-14 04:34 UTC, Vilkas99 commented on src/components/popOver/index.tsx
> +        <AlertDialogContent maxW={calculateWidth(size) + "px"}>
No estaría mal mover todo el contenido del Alert, a su propio subcomponente (Para que no se vea enorme el componente de alerta que de por sí ya tiene muchas props! :D ) - Pero eso te lo dejo a tu discreción.

2022-04-14 04:43 UTC, Vilkas99 requested changes
Súper bien el código! Sólo unos cuantos detalles.

2022-04-14 04:43 UTC, Vilkas99 commented on src/components/radioArray/index.tsx
> +    <Radio colorScheme={"pink"} value={radioButton.value}>
Me encanta esta función! Únicamente le añadiría al componente una forma en la que el usuario pueda añadirle props de configuración general (Como tamaño, color, etc...) desde que se le invoque (Y no modificando el código directamente) 

Para ello, puedes añadir una prop (Y con ello un tipo a tu interfaz) que se llame "baseProps", el cual será un objeto con keys (string) y valores (any) que le permitirán al programador configurar las propiedades base de un componente tipo "Radio" desde "afuera") 

Ejemplo: 

`interface IRadioArray {..., baseProps: {[key:string]:any}}`

Y después en tú código del radio array, deconstruyes ese objeto para que todas sus propiedades se esparzan en el objeto en cuestión: 

`const RadioArray = ({..., baseProps}) => ({
{...}
<Radio {...baseProps}/>
})`

Nótese que este ejemplo omite muchas partes de tu código, y es únicamente ilustrativo :D

2022-04-14 04:43 UTC, Vilkas99 commented on src/components/radioArray/index.tsx
> +import { Radio, RadioGroup, Stack } from "@chakra-ui/react";
Aquí el orden también está incorrecto (Retomar comentario anterior/similar en donde se habla del orden correcto de la importación)

2022-04-14 05:34 UTC, myrosandrade89 commented on src/App.tsx
> +        size={"s"}
Ya está corregido en la última versión

2022-04-14 05:34 UTC, myrosandrade89 commented on src/components/popOver/index.tsx
> +import {
Ya está corregido en la última versión

2022-04-14 05:41 UTC, myrosandrade89 commented on src/components/popOver/index.tsx
> +        <AlertDialogContent maxW={calculateWidth(size) + "px"}>
Considero que es correcto de esta forma :D

2022-04-14 05:44 UTC, myrosandrade89 commented on src/components/radioArray/index.tsx
> +    <Radio colorScheme={"pink"} value={radioButton.value}>
Sí consideré que fuera totalmente personalizable, pero decidí que lo mejor era limitar las opciones de configuración para que la interfaz mantenga un estilo uniforme.

2022-04-14 05:45 UTC, myrosandrade89 commented on src/components/radioArray/index.tsx
> +import { Radio, RadioGroup, Stack } from "@chakra-ui/react";
Ya está corregido en la última versión

2022-04-14 05:54 UTC, myrosandrade89 commented on src/components/popOver/index.tsx
> +  const calculateWidth = (size: string) => {
Ya está corregido en la última versión

2022-04-14 05:54 UTC, myrosandrade89 commented on src/components/popOver/index.tsx
> +    if (size == "s") {
Ya está corregido en la última versión

2022-04-15 03:44 UTC, Vilkas99 approved these changes

2022-04-15 03:44 UTC, Vilkas99 commented on src/components/popOver/index.tsx
> +export enum ETypeSize {
Posteriormente añadir este enum en la carpeta de "enums" dentro de "interfaces" .

2022-04-15 03:44 UTC, merged