Profile Card / Progress Bar / Dropdown
Fer-Rodriguez/PAE pull request #4
Opened 2022-04-14 04:22 UTC by Vilkas99

Done.

2022-04-14 06:21 UTC, myrosandrade89 requested changes
Considero que para algunos componentes se deberían utilizar como base los componentes Button y Card de Fer y sólo modificar el contenido para no duplicar esfuerzos :)

2022-04-14 06:21 UTC, myrosandrade89 commented on src/components/ProfileCard/index.tsx
> +      height={
Recuerda que para maximizar responsividad es mejor definir una altura máxima en lugar de una altura definida. Especialmente porque no hay comportamiento de overflow definido.

2022-04-14 06:21 UTC, myrosandrade89 commented on src/components/ProfileCard/index.tsx
> +      width={"50rem"}
En el componente que yo hice utilicé porcentajes y le recomendé lo mismo a Fer. Sería bueno que todos usáramos el mismo estándar para la unidad del width.

2022-04-14 06:21 UTC, myrosandrade89 commented on src/components/ProfileCard/index.tsx
> +//Interfaces, Types & Enums
Considero que para este componente se deberían utilizar como base los componentes Button y Card de Fer y sólo modificar el contenido para no duplicar esfuerzos :)

2022-04-14 06:21 UTC, myrosandrade89 commented on src/pages/Dashboard/title.component.tsx
> +import { useEffect } from "react";
Regresar este archivo a su versión previa. El contenido actual es de prueba.

2022-04-15 03:47 UTC, Vilkas99 commented on src/components/ProfileCard/index.tsx
> +      width={"50rem"}
Completamente de acuerdo! Procedo a cambiarlo:)

2022-04-15 03:49 UTC, Vilkas99 commented on src/components/ProfileCard/index.tsx
> +//Interfaces, Types & Enums
Justo Myros! Pero para ello necesito que se apruebe la branch de Fer y con ello yo pueda hacer pull a sus cambios (De lo contrario, es imposible que acceda a sus componentes) - Te parece que esto lo dejemos para un punto posterior de desarrollo?:)

2022-04-15 03:55 UTC, Vilkas99 commented on src/components/ProfileCard/index.tsx
> +      height={
Perfecto! Procedo a corregirlo :)

2022-04-15 03:55 UTC, Vilkas99 commented on src/components/Dropdown/index.tsx
> +const customOptionStyle = (index: number, type: ETypeDropdown) => {
Procedo a corregirlo wujuu!

2022-04-15 17:24 UTC, myrosandrade89 commented on src/components/ProfileCard/index.tsx
> +//Interfaces, Types & Enums
Me parece bien :D

2022-04-15 17:24 UTC, myrosandrade89 approved these changes

2022-04-15 17:39 UTC, merged