Menú, text input y boton de info
Fer-Rodriguez/PAE pull request #5
Opened 2022-04-14 11:55 UTC by alexlohe25

2022-04-15 04:38 UTC, Vilkas99 requested changes
- [x] Modificar los imports. 
- [x] Eliminar la llamada de componentes en App. 
- [ ] Transformar un componente funcional declarativo en uno de función anónima,

2022-04-15 04:38 UTC, Vilkas99 commented on src/App.tsx
>        <Menu />
Eliminar la llamada de estos componentes en el App (Ya que sólo se utilizan para testing, y no estarán llamados directamente en el componente)

2022-04-15 04:38 UTC, Vilkas99 commented on src/App.tsx
El orden de los imports es incorrecto: 

1. Todo lo importado de React. 
2. Todo lo importado de librerías externas (Por ejemplo; todo lo de chakra) 
3. Todo lo importado de los componentes propios. 
4. Interfaces, tipos y enums.

2022-04-15 04:38 UTC, Vilkas99 commented on src/components/Info_Button/index.tsx
> +function Info_Button() {
Este componente no está construida con una función anónima (Recuerda utilizar el snippet RAFC para poder crear este tipo de componente)

2022-04-15 04:41 UTC, Vilkas99 requested changes
- [ ] Orden de los imports. 
- [ ] Transformar a función anónima
- [ ] Eliminar "{}" y "return"

2022-04-15 04:41 UTC, Vilkas99 commented on src/components/Menu/index.tsx
> +import { Center, Image, Stack, HStack, VStack } from "@chakra-ui/react";
El orden está incorrecto (Remitirse a comentarios anteriores para evaluar el orden correcto)

2022-04-15 04:41 UTC, Vilkas99 commented on src/components/Menu/index.tsx
>  function Menu() {
Transformar a función anónima.

2022-04-15 04:41 UTC, Vilkas99 commented on src/components/Menu/index.tsx
>  function Menu() {
También, en caso de que no utilices lógica, puedes omitir el uso de "{}" que encierran a todo el contenido de "Menu" al igual que el "return" si en lugar de usar las "{}", utilizas "()". 

Por ejemplo: `const ComponenteSinLogicaCompleja = () => (<h1>WOW</h1>)`

2022-04-15 16:22 UTC, myrosandrade89 commented on src/components/Menu/index.tsx
> +        borderRadius="25px"
Posteriormente hay que cambiar estas propiedas (border radius, bg, etc.) con el tema

2022-04-15 16:23 UTC, myrosandrade89 requested changes

2022-04-15 16:23 UTC, myrosandrade89 commented on src/components/Text_Input/index.tsx
> +function Text_Input({ placeholderText, width }: ITextInput) {
Este componente no está construida con una función anónima (Recuerda utilizar el snippet RAFC para poder crear este tipo de componente)

2022-04-16 17:08 UTC, myrosandrade89 approved these changes

2022-04-18 15:59 UTC, merged